name: bankruptcy-test
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.10
  - ipykernel
  - pandas
  - scikit-learn
  - imbalanced-learn
  - matplotlib
